INSERT INTO states (name, uf, slug) VALUES
('Acre', 'AC', 'acre'),
('Alagoas', 'AL', 'alagoas'),
('Amapá', 'AP', 'amapa'),
('Amazonas', 'AM', 'amazonas'),
('Bahia', 'BA', 'bahia'),
('Ceará', 'CE', 'ceara'),
('Distrito Federal', 'DF', 'distrito-federal'),
('Espírito Santo', 'ES', 'espirito-santo'),
('Goiás', 'GO', 'goias'),
('Maranhão', 'MA', 'maranhao'),
('Mato Grosso', 'MT', 'mato-grosso'),
('Mato Grosso do Sul', 'MS', 'mato-grosso-do-sul'),
('Minas Gerais', 'MG', 'minas-gerais'),
('Pará', 'PA', 'para'),
('Paraíba', 'PB', 'paraiba'),
('Paraná', 'PR', 'parana'),
('Pernambuco', 'PE', 'pernambuco'),
('Piauí', 'PI', 'piaui'),
('Rio de Janeiro', 'RJ', 'rio-de-janeiro'),
('Rio Grande do Norte', 'RN', 'rio-grande-do-norte'),
('Rio Grande do Sul', 'RS', 'rio-grande-do-sul'),
('Rondônia', 'RO', 'rondonia'),
('Roraima', 'RR', 'roraima'),
('Santa Catarina', 'SC', 'santa-catarina'),
('São Paulo', 'SP', 'sao-paulo'),
('Sergipe', 'SE', 'sergipe'),
('Tocantins', 'TO', 'tocantins');
